workflow:
  general:
    name: mlp_strategy
    lab_dir: ./lab/csi300
    index_symbol: 000300.SSE
    start: "2007-01-01"
    end: "2024-10-31"
    interval: daily
    extended_days: 100
    train_period: ["2007-01-01", "2020-12-31"]
    valid_period: ["2021-01-01", "2021-12-31"]
    test_period: ["2022-01-01", "2024-10-31"]

  steps:
    - type: load_data
      enabled: false

    - type: process_features
      enabled: false
      config: {}

    - type: train_model
      enabled: true
      model: MlpModel
      config:
        input_size: 158
        hidden_sizes: [256]
        lr: 0.002
        optimizer: adam
        n_epochs: 50
        batch_size: 8192
        weight_decay: 0.0002
        seed: 42
        device: cpu

    - type: predict_signal
      enabled: false
      config: {}

    - type: backtesting
      enabled: false
      config:
        interval: daily
        start: "2022-01-01"
        end: "2024-10-31"
        capital: 100000000
        setting:
          top_k: 30
          n_drop: 3
          hold_thresh: 3
          signal_name: "mlp_strategy" 